const DEFAULT_ERROR = 500;
const NOT_FOUND_ERROR = 404;
const BAD_REQUEST_ERROR = 400;
const CONFLICT_ERROR = 409;
const AUTHORIZATION_ERROR = 401;
const FORBIDDEN_ERROR = 403;

module.exports = {
  DEFAULT_ERROR,
  NOT_FOUND_ERROR,
  BAD_REQUEST_ERROR,
  CONFLICT_ERROR,
  AUTHORIZATION_ERROR,
  FORBIDDEN_ERROR,
};
